### ISSUE TITLE
handle non-existent repository source

### ISSUE THREAD

**Issue by aaronjanse** [sifive/wit#122]
Current error output when running `repo_path.t`:
<details><pre>
Traceback (most recent call last):
  File "/nix/store/jk588wcj1wg51kv2af3rb2j7lkl8h9b0-python3-3.5.7/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nix/store/jk588wcj1wg51kv2af3rb2j7lkl8h9b0-python3-3.5.7/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aaronj/wit/lib/wit/__main__.py", line 11, in <module>
    main()
  File "/Users/aaronj/wit/lib/wit/main.py", line 114, in main
    create(args)
  File "/Users/aaronj/wit/lib/wit/main.py", line 185, in create
    update(ws, args)
  File "/Users/aaronj/wit/lib/wit/main.py", line 347, in update
    packages, errors = ws.resolve(download=True)
  File "/Users/aaronj/wit/lib/wit/workspace.py", line 117, in resolve
    source_map, packages, queue, errors)
  File "/Users/aaronj/wit/lib/wit/common.py", line 11, in new
    return func(self, *copy_args, **copy_kwargs)
  File "/Users/aaronj/wit/lib/wit/dependency.py", line 30, in resolve_deps
    subdep.package.load_repo(wsroot, download, subdep.specified_revision)
  File "/Users/aaronj/wit/lib/wit/package.py", line 88, in load_repo
    self.repo.download()
  File "/Users/aaronj/wit/lib/wit/gitrepo.py", line 75, in download
    self.clone()
  File "/Users/aaronj/wit/lib/wit/gitrepo.py", line 86, in clone
    self._git_check(proc)
  File "/Users/aaronj/wit/lib/wit/gitrepo.py", line 239, in _git_check
    raise GitError(msg)
wit.gitrepo.GitError: Command [git clone --no-checkout /Users/aaronj/wit/t/foo /Users/aaronj/wit/t/myws/.wit/foo] exited with non-zero exit status [128]
stdout: []
stderr: [fatal: repository '/Users/aaronj/wit/t/foo' does not exist]
</pre></details>

---

Maybe we should tell Wit users to report all stacktraces they see. For each stacktrace, we could either improve the error logging and/or fix a bug.

**Comment by aaronjanse** [comment]
Fixed by [`bad-source-error`](https://github.com/sifive/wit/compare/non-fatal-errors2...bad-source-error)
Pending on #123
