### ISSUE TITLE
handle "unknown revision or path"

### ISSUE THREAD

**Issue by aaronjanse** [sifive/wit#131]
Current stacktrace:
<details><pre>
Traceback (most recent call last):
  File "/Users/aaronj/wit/lib/wit/gitrepo.py", line 78, in get_commit
    self._git_check(proc)
  File "/Users/aaronj/wit/lib/wit/gitrepo.py", line 214, in _git_check
    raise GitError(msg)
wit.gitrepo.GitError: Command [git rev-parse cfce5c1] exited with non-zero exit status [128]
stdout: [cfce5c1]
stderr: [fatal: ambiguous argument 'cfce5c1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/jk588wcj1wg51kv2af3rb2j7lkl8h9b0-python3-3.5.7/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nix/store/jk588wcj1wg51kv2af3rb2j7lkl8h9b0-python3-3.5.7/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aaronj/wit/lib/wit/__main__.py", line 11, in <module>
    main()
  File "/Users/aaronj/wit/lib/wit/main.py", line 169, in main
    update_pkg(ws, args)
  File "/Users/aaronj/wit/lib/wit/main.py", line 240, in update_pkg
    ws.update_dependency(args.repo)
  File "/Users/aaronj/wit/lib/wit/workspace.py", line 268, in update_dependency
    req_resolved_rev = req_dep.resolved_rev()
  File "/Users/aaronj/wit/lib/wit/dependency.py", line 107, in resolved_rev
    return self.package.repo.get_commit(self.specified_revision)
  File "/Users/aaronj/wit/lib/wit/gitrepo.py", line 81, in get_commit
    self._git_check(proc)
  File "/Users/aaronj/wit/lib/wit/gitrepo.py", line 214, in _git_check
    raise GitError(msg)
wit.gitrepo.GitError: Command [git rev-parse origin/cfce5c1] exited with non-zero exit status [128]
stdout: [origin/cfce5c1]
stderr: [fatal: ambiguous argument 'origin/cfce5c1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]']
</pre></details>

**Comment by aaronjanse** [comment]
Fixed by [`commit-not-found`](https://github.com/sifive/wit/compare/non-fatal-errors2...commit-not-found)
Pending on #123
