### ISSUE TITLE
during wit add-pkg $FOO_PATH or wit add-pkg foo getting some error

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [sifive/wit#151]
following is the code which i got by comand mentioned in the subject of the issue, because of this it couldn't add package in the wit-workspace.json:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/shraddha/wit/lib/wit/__main__.py", line 11, in <module>
    main()
  File "/home/shraddha/wit/lib/wit/main.py", line 129, in main
    add_pkg(ws, args)
  File "/home/shraddha/wit/lib/wit/main.py", line 196, in add_pkg
    ws.add_dependency(args.repo)
  File "/home/shraddha/wit/lib/wit/workspace.py", line 196, in add_dependency
    dep = dependency_from_tag(self.root, tag)
  File "/home/shraddha/wit/lib/wit/main.py", line 208, in dependency_from_tag
    source = repo.get_remote()
  File "/home/shraddha/wit/lib/wit/gitrepo.py", line 139, in get_remote
    self._git_check(proc)
  File "/home/shraddha/wit/lib/wit/gitrepo.py", line 248, in _git_check
    raise GitError(msg)
wit.gitrepo.GitError: Command [git remote get-url origin] exited with non-zero exit status [128]
stdout: []
stderr: [fatal: No such remote 'origin']

**Comment by ShraddhaDevaiya** [comment]
Please give or suggest me some solution for this as soon as possible, because I am stuck here since last 4 days.

**Comment by ShraddhaDevaiya** [comment]
Resolved. It is working fine, now.
